title: Product Tax Rate
description: >-
  Associates a tax rate with a product to indicate that the product is taxed in
  a certain way
x-resourceId: product_tax_rate
type: object
required:
  - product_id
  - rate_id
properties:
  product_id:
    description: The ID of the Product
    type: string
    example: prod_01G1G5V2MBA328390B5AXJ610F
  product:
    description: Available if the relation `product` is expanded.
    $ref: ./product.yaml
  rate_id:
    description: The ID of the Tax Rate
    type: string
    example: txr_01G8XDBAWKBHHJRKH0AV02KXBR
  tax_rate:
    description: Available if the relation `tax_rate` is expanded.
    $ref: ./tax_rate.yaml
  created_at:
    type: string
    description: The date with timezone at which the resource was created.
    format: date-time
  updated_at:
    type: string
    description: The date with timezone at which the resource was updated.
    format: date-time
  metadata:
    type: object
    description: An optional key-value map with additional details
    example:
      car: white
