title: ProductCategory
description: Represents a product category
x-resourceId: ProductCategory
type: object
required:
  - name
properties:
  id:
    type: string
    description: The product category's ID
    example: pcat_01G2SG30J8C85S4A5CHM2S1NS2
  name:
    type: string
    description: The product category's name
    example: Regular Fit
  handle:
    description: 'A unique string that identifies the Category - example: slug structures.'
    type: string
    example: regular-fit
  mpath:
    type: string
    description: >-
      A string for Materialized Paths - used for finding ancestors and
      descendents
    example: pcat_id1.pcat_id2.pcat_id3
  is_internal:
    type: boolean
    description: A flag to make product category an internal category for admins
    default: false
  is_active:
    type: boolean
    description: A flag to make product category visible/hidden in the store front
    default: false
  category_children:
    description: Available if the relation `category_children` are expanded.
    type: array
    items:
      type: object
      description: A product category object.
  parent_category_id:
    description: The ID of the parent category.
    type: string
    default: null
  parent_category:
    description: >-
      A product category object. Available if the relation `parent_category` is
      expanded.
    type: object
  products:
    description: >-
      products associated with category. Available if the relation `products` is
      expanded.
    type: array
    items:
      type: object
      description: A product object.
  created_at:
    type: string
    description: The date with timezone at which the resource was created.
    format: date-time
  updated_at:
    type: string
    description: The date with timezone at which the resource was updated.
    format: date-time
  deleted_at:
    type: string
    description: The date with timezone at which the resource was deleted.
    format: date-time
