title: Product Type
description: Product Type can be added to Products for filtering and reporting purposes.
x-resourceId: product_type
required:
  - value
properties:
  id:
    type: string
    description: The product type's ID
    example: ptyp_01G8X9A7ESKAJXG2H0E6F1MW7A
  value:
    description: The value that the Product Type represents.
    type: string
    example: Clothing
  created_at:
    type: string
    description: The date with timezone at which the resource was created.
    format: date-time
  updated_at:
    type: string
    description: The date with timezone at which the resource was updated.
    format: date-time
  deleted_at:
    type: string
    description: The date with timezone at which the resource was deleted.
    format: date-time
  metadata:
    type: object
    description: An optional key-value map with additional details
    example:
      car: white
