title: ProductCategory
description: Represents a product category
x-resourceId: ProductCategory
type: object
required:
  - category_children
  - created_at
  - handle
  - id
  - is_active
  - is_internal
  - mpath
  - name
  - parent_category_id
  - updated_at
properties:
  id:
    description: The product category's ID
    type: string
    example: pcat_01G2SG30J8C85S4A5CHM2S1NS2
  name:
    description: The product category's name
    type: string
    example: Regular Fit
  handle:
    description: >-
      A unique string that identifies the Product Category - can for example be
      used in slug structures.
    type: string
    example: regular-fit
  mpath:
    description: >-
      A string for Materialized Paths - used for finding ancestors and
      descendents
    nullable: true
    type: string
    example: pcat_id1.pcat_id2.pcat_id3
  is_internal:
    type: boolean
    description: A flag to make product category an internal category for admins
    default: false
  is_active:
    type: boolean
    description: A flag to make product category visible/hidden in the store front
    default: false
  rank:
    type: integer
    description: An integer that depicts the rank of category in a tree node
    default: 0
  category_children:
    description: Available if the relation `category_children` are expanded.
    type: array
    items:
      type: object
  parent_category_id:
    description: The ID of the parent category.
    nullable: true
    type: string
    default: null
  parent_category:
    description: >-
      A product category object. Available if the relation `parent_category` is
      expanded.
    nullable: true
    type: object
  products:
    description: >-
      Products associated with category. Available if the relation `products` is
      expanded.
    type: array
    items:
      type: object
  created_at:
    description: The date with timezone at which the resource was created.
    type: string
    format: date-time
  updated_at:
    description: The date with timezone at which the resource was updated.
    type: string
    format: date-time
