get:
  operationId: GetProductTags
  summary: List Product Tags
  description: Retrieve a list of Product Tags.
  x-authenticated: true
  parameters:
    - in: query
      name: limit
      description: The number of types to return.
      schema:
        type: integer
        default: 20
    - in: query
      name: offset
      description: The number of items to skip before the results.
      schema:
        type: integer
        default: 0
    - in: query
      name: order
      description: The field to sort items by.
      schema:
        type: string
    - in: query
      name: discount_condition_id
      description: The discount condition id on which to filter the product tags.
      schema:
        type: string
    - in: query
      name: value
      style: form
      explode: false
      description: The tag values to search for
      schema:
        type: array
        items:
          type: string
    - in: query
      name: id
      style: form
      explode: false
      description: The tag IDs to search for
      schema:
        type: array
        items:
          type: string
    - in: query
      name: q
      description: A query string to search values for
      schema:
        type: string
    - in: query
      name: created_at
      description: Date comparison for when resulting product tags were created.
      schema:
        type: object
        properties:
          lt:
            type: string
            description: filter by dates less than this date
            format: date
          gt:
            type: string
            description: filter by dates greater than this date
            format: date
          lte:
            type: string
            description: filter by dates less than or equal to this date
            format: date
          gte:
            type: string
            description: filter by dates greater than or equal to this date
            format: date
    - in: query
      name: updated_at
      description: Date comparison for when resulting product tags were updated.
      schema:
        type: object
        properties:
          lt:
            type: string
            description: filter by dates less than this date
            format: date
          gt:
            type: string
            description: filter by dates greater than this date
            format: date
          lte:
            type: string
            description: filter by dates less than or equal to this date
            format: date
          gte:
            type: string
            description: filter by dates greater than or equal to this date
            format: date
  x-codeSamples:
    - lang: JavaScript
      label: JS Client
      source:
        $ref: ../code_samples/JavaScript/product-tags/getundefined
    - lang: Shell
      label: cURL
      source:
        $ref: ../code_samples/Shell/product-tags/getundefined
  tags:
    - Product Tag
  responses:
    '200':
      description: OK
      content:
        application/json:
          schema:
            type: object
            properties:
              product_tags:
                $ref: ../components/schemas/ProductTag.yaml
              count:
                type: integer
                description: The total number of items available
              offset:
                type: integer
                description: The number of items skipped before these items
              limit:
                type: integer
                description: The number of items per page
    '400':
      $ref: ../components/responses/400_error.yaml
    '401':
      $ref: ../components/responses/unauthorized.yaml
    '404':
      $ref: ../components/responses/not_found_error.yaml
    '409':
      $ref: ../components/responses/invalid_state_error.yaml
    '422':
      $ref: ../components/responses/invalid_request_error.yaml
    '500':
      $ref: ../components/responses/500_error.yaml
