get:
  operationId: GetProductCategories
  summary: List Product Categories
  description: Retrieve a list of product categories.
  x-authenticated: false
  parameters:
    - in: query
      name: q
      description: Query used for searching product category names orhandles.
      schema:
        type: string
    - in: query
      name: parent_category_id
      description: Returns categories scoped by parent
      schema:
        type: string
    - in: query
      name: offset
      description: How many product categories to skip in the result.
      schema:
        type: integer
        default: 0
    - in: query
      name: limit
      description: Limit the number of product categories returned.
      schema:
        type: integer
        default: 100
  x-codeSamples:
    - lang: Shell
      label: cURL
      source:
        $ref: ../code_samples/Shell/product-categories/getundefined
  security:
    - api_token: []
    - cookie_auth: []
  tags:
    - Product Category
  responses:
    '200':
      description: OK
      content:
        application/json:
          schema:
            type: object
            properties:
              product_categories:
                type: array
                items:
                  $ref: ../components/schemas/ProductCategory.yaml
              count:
                type: integer
                description: The total number of items available
              offset:
                type: integer
                description: The number of items skipped before these items
              limit:
                type: integer
                description: The number of items per page
    '400':
      $ref: ../components/responses/400_error.yaml
    '401':
      $ref: ../components/responses/unauthorized.yaml
    '404':
      $ref: ../components/responses/not_found_error.yaml
    '409':
      $ref: ../components/responses/invalid_state_error.yaml
    '422':
      $ref: ../components/responses/invalid_request_error.yaml
    '500':
      $ref: ../components/responses/500_error.yaml
