get:
  operationId: GetProductsProduct
  summary: Get a Product
  description: Retrieves a Product.
  parameters:
    - in: path
      name: id
      required: true
      description: The id of the Product.
      schema:
        type: string
  x-codeSamples:
    - lang: JavaScript
      label: JS Client
      source:
        $ref: ../code_samples/JavaScript/products_{id}/getundefined
    - lang: Shell
      label: cURL
      source:
        $ref: ../code_samples/Shell/products_{id}/getundefined
  tags:
    - Product
  responses:
    '200':
      description: OK
      content:
        application/json:
          schema:
            properties:
              product:
                $ref: ../components/schemas/product.yaml
    '400':
      $ref: ../components/responses/400_error.yaml
    '404':
      $ref: ../components/responses/not_found_error.yaml
    '409':
      $ref: ../components/responses/invalid_state_error.yaml
    '422':
      $ref: ../components/responses/invalid_request_error.yaml
    '500':
      $ref: ../components/responses/500_error.yaml
