title: Product variants
domain: store
routes:
  - method: GET
    path: /product-variants
  - method: GET
    path: /product-variants/:id
route: /product-variants
description: >
  A product variant represents a specific type of product. E.g. a variant can differ from other variants based on size and color. A variant will always belong to a product.
endpoints:
  - path: /:id
    method: GET
    title: Retrieve product variant
    params:
      - name: id
        type: String
        description: Id of the product variant.
    description: >
      Retrieves product variant
  - path: /
    method: GET
    title: List product variants
    params:
      - name: ids
        optional: true
        type: String
        description: String of product variant ids. Id's needs to be separated by comma.
    description: >
      Retrieves product variants. Specific variants can be retrieved using `ids` query param in the request.

response: |
  {
    "region": {
      "id": "reg_HMnixPlOicAs7aBlXuchAGxd",
      "name": "Denmark",
      "currency_code": "DKK",
      "currency": "DKK",
      "tax_rate": 0.25,
      "tax_code": null,
      "countries": [{
        "id": "1001",
        "iso_2": "DK",
        "iso_3": "DNK",
        "num_code": "208",
        "name": "denmark",
        "display_name": "Denmark"
      }],
      "payment_providers": [{
        "id": "stripe",
        "is_installed": true
      }],
      "fulfillment_providers": [{
        "id": "manual",
        "is_installed": true
      }],
      "created_at": "2020-12-11T17:03:54.458Z",
      "updated_at": "2020-12-11T17:03:54.458Z",
      "metadata": null
    }
  }
