title: Products
domain: store
routes:
  - method: POST
    path: /products
  - method: GET
    path: /products/:id
route: /products
description: >
  A product represents the object, that are to be sold on the website. A product can have variants, that differ by e.g. size and color.
endpoints:
  - path: /:id
    method: GET
    title: Retrieve product
    params:
      - name: id
        type: String
        description: Id of the product.
    description: >
      Retrieves a product
  - path: /
    method: GET
    title: List products
    description: >
      Retrieves the products for the configured store.

response: |
  {
    "region": {
      "id": "reg_HMnixPlOicAs7aBlXuchAGxd",
      "name": "Denmark",
      "currency_code": "DKK",
      "currency": "DKK",
      "tax_rate": 0.25,
      "tax_code": null,
      "countries": [{
        "id": "1001",
        "iso_2": "DK",
        "iso_3": "DNK",
        "num_code": "208",
        "name": "denmark",
        "display_name": "Denmark"
      }],
      "payment_providers": [{
        "id": "stripe",
        "is_installed": true
      }],
      "fulfillment_providers": [{
        "id": "manual",
        "is_installed": true
      }],
      "created_at": "2020-12-11T17:03:54.458Z",
      "updated_at": "2020-12-11T17:03:54.458Z",
      "metadata": null
    }
  }
