delete:
  operationId: DeleteProductsProduct
  summary: Delete a Product
  description: Deletes a Product and it's associated Product Variants.
  x-authenticated: true
  parameters:
    - in: path
      name: id
      required: true
      description: The ID of the Product.
      schema:
        type: string
  x-codeSamples:
    - lang: JavaScript
      label: JS Client
      source:
        $ref: ../code_samples/JavaScript/products_{id}/deleteundefined
    - lang: Shell
      label: cURL
      source:
        $ref: ../code_samples/Shell/products_{id}/deleteundefined
  security:
    - api_token: []
    - cookie_auth: []
  tags:
    - Product
  responses:
    '200':
      description: OK
      content:
        application/json:
          schema:
            properties:
              id:
                type: string
                description: The ID of the deleted Product.
              object:
                type: string
                description: The type of the object that was deleted.
                default: product
              deleted:
                type: boolean
                description: Whether or not the items were deleted.
                default: true
    '400':
      $ref: ../components/responses/400_error.yaml
    '401':
      $ref: ../components/responses/unauthorized.yaml
    '404':
      $ref: ../components/responses/not_found_error.yaml
    '409':
      $ref: ../components/responses/invalid_state_error.yaml
    '422':
      $ref: ../components/responses/invalid_request_error.yaml
    '500':
      $ref: ../components/responses/500_error.yaml
get:
  operationId: GetProductsProduct
  summary: Retrieve a Product
  description: Retrieves a Product.
  x-authenticated: true
  parameters:
    - in: path
      name: id
      required: true
      description: The ID of the Product.
      schema:
        type: string
  x-codeSamples:
    - lang: JavaScript
      label: JS Client
      source:
        $ref: ../code_samples/JavaScript/products_{id}/getundefined
    - lang: Shell
      label: cURL
      source:
        $ref: ../code_samples/Shell/products_{id}/getundefined
  security:
    - api_token: []
    - cookie_auth: []
  tags:
    - Product
  responses:
    '200':
      description: OK
      content:
        application/json:
          schema:
            properties:
              product:
                $ref: ../components/schemas/product.yaml
    '400':
      $ref: ../components/responses/400_error.yaml
    '401':
      $ref: ../components/responses/unauthorized.yaml
    '404':
      $ref: ../components/responses/not_found_error.yaml
    '409':
      $ref: ../components/responses/invalid_state_error.yaml
    '422':
      $ref: ../components/responses/invalid_request_error.yaml
    '500':
      $ref: ../components/responses/500_error.yaml
post:
  operationId: PostProductsProduct
  summary: Update a Product
  description: Updates a Product
  x-authenticated: true
  parameters:
    - in: path
      name: id
      required: true
      description: The ID of the Product.
      schema:
        type: string
  requestBody:
    content:
      application/json:
        schema:
          properties:
            title:
              description: The title of the Product
              type: string
            subtitle:
              description: The subtitle of the Product
              type: string
            description:
              description: A description of the Product.
              type: string
            discountable:
              description: >-
                A flag to indicate if discounts can be applied to the LineItems
                generated from this Product
              type: boolean
            images:
              description: Images of the Product.
              type: array
              items:
                type: string
            thumbnail:
              description: The thumbnail to use for the Product.
              type: string
            handle:
              description: A unique handle to identify the Product by.
              type: string
            status:
              description: The status of the product.
              type: string
              enum:
                - draft
                - proposed
                - published
                - rejected
            type:
              description: The Product Type to associate the Product with.
              type: object
              required:
                - value
              properties:
                id:
                  description: The ID of the Product Type.
                  type: string
                value:
                  description: The value of the Product Type.
                  type: string
            collection_id:
              description: The ID of the Collection the Product should belong to.
              type: string
            tags:
              description: Tags to associate the Product with.
              type: array
              items:
                required:
                  - value
                properties:
                  id:
                    description: The ID of an existing Tag.
                    type: string
                  value:
                    description: The value of the Tag, these will be upserted.
                    type: string
            sales_channels:
              description: '[EXPERIMENTAL] Sales channels to associate the Product with.'
              type: array
              items:
                required:
                  - id
                properties:
                  id:
                    description: The ID of an existing Sales channel.
                    type: string
            variants:
              description: A list of Product Variants to create with the Product.
              type: array
              items:
                properties:
                  id:
                    description: The ID of the Product Variant.
                    type: string
                  title:
                    description: The title to identify the Product Variant by.
                    type: string
                  sku:
                    description: The unique SKU for the Product Variant.
                    type: string
                  ean:
                    description: The EAN number of the item.
                    type: string
                  upc:
                    description: The UPC number of the item.
                    type: string
                  barcode:
                    description: A generic GTIN field for the Product Variant.
                    type: string
                  hs_code:
                    description: The Harmonized System code for the Product Variant.
                    type: string
                  inventory_quantity:
                    description: The amount of stock kept for the Product Variant.
                    type: integer
                  allow_backorder:
                    description: >-
                      Whether the Product Variant can be purchased when out of
                      stock.
                    type: boolean
                  manage_inventory:
                    description: >-
                      Whether Medusa should keep track of the inventory for this
                      Product Variant.
                    type: boolean
                  weight:
                    description: The wieght of the Product Variant.
                    type: number
                  length:
                    description: The length of the Product Variant.
                    type: number
                  height:
                    description: The height of the Product Variant.
                    type: number
                  width:
                    description: The width of the Product Variant.
                    type: number
                  origin_country:
                    description: The country of origin of the Product Variant.
                    type: string
                  mid_code:
                    description: >-
                      The Manufacturer Identification code for the Product
                      Variant.
                    type: string
                  material:
                    description: The material composition of the Product Variant.
                    type: string
                  metadata:
                    description: >-
                      An optional set of key-value pairs with additional
                      information.
                    type: object
                  prices:
                    type: array
                    items:
                      required:
                        - amount
                      properties:
                        id:
                          description: The ID of the Price.
                          type: string
                        region_id:
                          description: >-
                            The ID of the Region for which the price is used.
                            Only required if currency_code is not provided.
                          type: string
                        currency_code:
                          description: >-
                            The 3 character ISO currency code for which the
                            price will be used. Only required if region_id is
                            not provided.
                          type: string
                          externalDocs:
                            url: >-
                              https://en.wikipedia.org/wiki/ISO_4217#Active_codes
                            description: See a list of codes.
                        amount:
                          description: The amount to charge for the Product Variant.
                          type: integer
                        min_quantity:
                          description: >-
                            The minimum quantity for which the price will be
                            used.
                          type: integer
                        max_quantity:
                          description: >-
                            The maximum quantity for which the price will be
                            used.
                          type: integer
                  options:
                    type: array
                    items:
                      required:
                        - option_id
                        - value
                      properties:
                        option_id:
                          description: The ID of the Option.
                          type: string
                        value:
                          description: >-
                            The value to give for the Product Option at the same
                            index in the Product's `options` field.
                          type: string
            weight:
              description: The wieght of the Product.
              type: number
            length:
              description: The length of the Product.
              type: number
            height:
              description: The height of the Product.
              type: number
            width:
              description: The width of the Product.
              type: number
            origin_country:
              description: The country of origin of the Product.
              type: string
            mid_code:
              description: The Manufacturer Identification code for the Product.
              type: string
            material:
              description: The material composition of the Product.
              type: string
            metadata:
              description: An optional set of key-value pairs with additional information.
              type: object
  x-codeSamples:
    - lang: JavaScript
      label: JS Client
      source:
        $ref: ../code_samples/JavaScript/products_{id}/postundefined
    - lang: Shell
      label: cURL
      source:
        $ref: ../code_samples/Shell/products_{id}/postundefined
  security:
    - api_token: []
    - cookie_auth: []
  tags:
    - Product
  responses:
    '200':
      description: OK
      content:
        application/json:
          schema:
            properties:
              product:
                $ref: ../components/schemas/product.yaml
    '400':
      $ref: ../components/responses/400_error.yaml
    '401':
      $ref: ../components/responses/unauthorized.yaml
    '404':
      $ref: ../components/responses/not_found_error.yaml
    '409':
      $ref: ../components/responses/invalid_state_error.yaml
    '422':
      $ref: ../components/responses/invalid_request_error.yaml
    '500':
      $ref: ../components/responses/500_error.yaml
