post:
  operationId: PostProductsProductVariants
  summary: Create a Product Variant
  description: >-
    Creates a Product Variant. Each Product Variant must have a unique
    combination of Product Option Values.
  x-authenticated: true
  parameters:
    - in: path
      name: id
      required: true
      description: The ID of the Product.
      schema:
        type: string
  requestBody:
    content:
      application/json:
        schema:
          required:
            - title
            - prices
            - options
          properties:
            title:
              description: The title to identify the Product Variant by.
              type: string
            sku:
              description: The unique SKU for the Product Variant.
              type: string
            ean:
              description: The EAN number of the item.
              type: string
            upc:
              description: The UPC number of the item.
              type: string
            barcode:
              description: A generic GTIN field for the Product Variant.
              type: string
            hs_code:
              description: The Harmonized System code for the Product Variant.
              type: string
            inventory_quantity:
              description: The amount of stock kept for the Product Variant.
              type: integer
              default: 0
            allow_backorder:
              description: Whether the Product Variant can be purchased when out of stock.
              type: boolean
            manage_inventory:
              description: >-
                Whether Medusa should keep track of the inventory for this
                Product Variant.
              type: boolean
            weight:
              description: The wieght of the Product Variant.
              type: number
            length:
              description: The length of the Product Variant.
              type: number
            height:
              description: The height of the Product Variant.
              type: number
            width:
              description: The width of the Product Variant.
              type: number
            origin_country:
              description: The country of origin of the Product Variant.
              type: string
            mid_code:
              description: The Manufacturer Identification code for the Product Variant.
              type: string
            material:
              description: The material composition of the Product Variant.
              type: string
            metadata:
              description: An optional set of key-value pairs with additional information.
              type: object
            prices:
              type: array
              items:
                required:
                  - amount
                properties:
                  id:
                    description: The ID of the price.
                    type: string
                  region_id:
                    description: >-
                      The ID of the Region for which the price is used. Only
                      required if currency_code is not provided.
                    type: string
                  currency_code:
                    description: >-
                      The 3 character ISO currency code for which the price will
                      be used. Only required if region_id is not provided.
                    type: string
                    externalDocs:
                      url: https://en.wikipedia.org/wiki/ISO_4217#Active_codes
                      description: See a list of codes.
                  amount:
                    description: The amount to charge for the Product Variant.
                    type: integer
                  min_quantity:
                    description: The minimum quantity for which the price will be used.
                    type: integer
                  max_quantity:
                    description: The maximum quantity for which the price will be used.
                    type: integer
            options:
              type: array
              items:
                required:
                  - option_id
                  - value
                properties:
                  option_id:
                    description: The ID of the Product Option to set the value for.
                    type: string
                  value:
                    description: The value to give for the Product Option.
                    type: string
  tags:
    - Product
  responses:
    '200':
      description: OK
      content:
        application/json:
          schema:
            properties:
              product:
                $ref: ../components/schemas/product.yaml
get:
  operationId: GetProductsProductVariants
  summary: List a Product's Product Variants
  description: Retrieves a list of the Product Variants associated with a Product.
  x-authenticated: true
  parameters:
    - in: path
      name: id
      required: true
      description: ID of the product to search for the variants.
      schema:
        type: string
    - in: query
      name: fields
      description: Comma separated string of the column to select.
      schema:
        type: string
    - in: query
      name: expand
      description: Comma separated string of the relations to include.
      schema:
        type: string
    - in: query
      name: offset
      description: How many items to skip before the results.
      schema:
        type: integer
        default: 0
    - in: query
      name: limit
      description: Limit the number of items returned.
      schema:
        type: integer
        default: 100
  tags:
    - Product
  responses:
    '200':
      description: OK
      content:
        application/json:
          schema:
            properties:
              variants:
                type: array
                items:
                  $ref: ../components/schemas/product_variant.yaml
              count:
                type: integer
                description: The total number of items available
              offset:
                type: integer
                description: The number of items skipped before these items
              limit:
                type: integer
                description: The number of items per page
