get:
  operationId: GetProductsTagUsage
  summary: List Tags Usage Number
  description: Retrieves a list of Product Tags with how many times each is used.
  x-authenticated: true
  x-codeSamples:
    - lang: JavaScript
      label: JS Client
      source:
        $ref: ../code_samples/JavaScript/products_tag-usage/getundefined
    - lang: Shell
      label: cURL
      source:
        $ref: ../code_samples/Shell/products_tag-usage/getundefined
  security:
    - api_token: []
    - cookie_auth: []
  tags:
    - Product Tag
  responses:
    '200':
      description: OK
      content:
        application/json:
          schema:
            $ref: ../components/schemas/AdminProductsListTagsRes.yaml
    '400':
      $ref: ../components/responses/400_error.yaml
    '401':
      $ref: ../components/responses/unauthorized.yaml
    '404':
      $ref: ../components/responses/not_found_error.yaml
    '409':
      $ref: ../components/responses/invalid_state_error.yaml
    '422':
      $ref: ../components/responses/invalid_request_error.yaml
    '500':
      $ref: ../components/responses/500_error.yaml
