delete:
  operationId: DeleteProductsProductVariantsVariant
  summary: Delete a Product Variant
  description: Deletes a Product Variant.
  x-authenticated: true
  parameters:
    - in: path
      name: id
      required: true
      description: The ID of the Product.
      schema:
        type: string
    - in: path
      name: variant_id
      required: true
      description: The ID of the Product Variant.
      schema:
        type: string
  x-codeSamples:
    - lang: JavaScript
      label: JS Client
      source:
        $ref: >-
          ../code_samples/JavaScript/products_{id}_variants_{variant_id}/deleteundefined
    - lang: Shell
      label: cURL
      source:
        $ref: >-
          ../code_samples/Shell/products_{id}_variants_{variant_id}/deleteundefined
  security:
    - api_token: []
    - cookie_auth: []
  tags:
    - Product
  responses:
    '200':
      description: OK
      content:
        application/json:
          schema:
            $ref: ../components/schemas/AdminProductsDeleteVariantRes.yaml
    '400':
      $ref: ../components/responses/400_error.yaml
    '401':
      $ref: ../components/responses/unauthorized.yaml
    '404':
      $ref: ../components/responses/not_found_error.yaml
    '409':
      $ref: ../components/responses/invalid_state_error.yaml
    '422':
      $ref: ../components/responses/invalid_request_error.yaml
    '500':
      $ref: ../components/responses/500_error.yaml
post:
  operationId: PostProductsProductVariantsVariant
  summary: Update a Product Variant
  description: Update a Product Variant.
  x-authenticated: true
  parameters:
    - in: path
      name: id
      required: true
      description: The ID of the Product.
      schema:
        type: string
    - in: path
      name: variant_id
      required: true
      description: The ID of the Product Variant.
      schema:
        type: string
  requestBody:
    content:
      application/json:
        schema:
          $ref: >-
            ../components/schemas/AdminPostProductsProductVariantsVariantReq.yaml
  x-codeSamples:
    - lang: JavaScript
      label: JS Client
      source:
        $ref: >-
          ../code_samples/JavaScript/products_{id}_variants_{variant_id}/postundefined
    - lang: Shell
      label: cURL
      source:
        $ref: >-
          ../code_samples/Shell/products_{id}_variants_{variant_id}/postundefined
  security:
    - api_token: []
    - cookie_auth: []
  tags:
    - Product
  responses:
    '200':
      description: OK
      content:
        application/json:
          schema:
            $ref: ../components/schemas/AdminProductsRes.yaml
    '400':
      $ref: ../components/responses/400_error.yaml
    '401':
      $ref: ../components/responses/unauthorized.yaml
    '404':
      $ref: ../components/responses/not_found_error.yaml
    '409':
      $ref: ../components/responses/invalid_state_error.yaml
    '422':
      $ref: ../components/responses/invalid_request_error.yaml
    '500':
      $ref: ../components/responses/500_error.yaml
