post:
  operationId: PostProductsProductOptions
  summary: Add an Option
  x-authenticated: true
  description: Adds a Product Option to a Product
  parameters:
    - in: path
      name: id
      required: true
      description: The ID of the Product.
      schema:
        type: string
  requestBody:
    content:
      application/json:
        schema:
          required:
            - title
          properties:
            title:
              description: The title the Product Option will be identified by i.e. "Size"
              type: string
  tags:
    - Product
  responses:
    '200':
      description: OK
      content:
        application/json:
          schema:
            properties:
              product:
                $ref: ../components/schemas/product.yaml
