post:
  operationId: PostProducts
  summary: Create a Product
  x-authenticated: true
  description: Creates a Product
  requestBody:
    content:
      application/json:
        schema:
          required:
            - title
          properties:
            title:
              description: The title of the Product
              type: string
            subtitle:
              description: The subtitle of the Product
              type: string
            description:
              description: A description of the Product.
              type: string
            is_giftcard:
              description: >-
                A flag to indicate if the Product represents a Gift Card.
                Purchasing Products with this flag set to `true` will result in
                a Gift Card being created.
              type: boolean
              default: false
            discountable:
              description: >-
                A flag to indicate if discounts can be applied to the LineItems
                generated from this Product
              type: boolean
              default: true
            images:
              description: Images of the Product.
              type: array
              items:
                type: string
            thumbnail:
              description: The thumbnail to use for the Product.
              type: string
            handle:
              description: A unique handle to identify the Product by.
              type: string
            status:
              description: The status of the product.
              type: string
              enum:
                - draft
                - proposed
                - published
                - rejected
              default: draft
            type:
              description: The Product Type to associate the Product with.
              type: object
              required:
                - value
              properties:
                id:
                  description: The ID of the Product Type.
                  type: string
                value:
                  description: The value of the Product Type.
                  type: string
            collection_id:
              description: The ID of the Collection the Product should belong to.
              type: string
            tags:
              description: Tags to associate the Product with.
              type: array
              items:
                required:
                  - value
                properties:
                  id:
                    description: The ID of an existing Tag.
                    type: string
                  value:
                    description: The value of the Tag, these will be upserted.
                    type: string
            sales_channels:
              description: '[EXPERIMENTAL] Sales channels to associate the Product with.'
              type: array
              items:
                required:
                  - id
                properties:
                  id:
                    description: The ID of an existing Sales channel.
                    type: string
            options:
              description: >-
                The Options that the Product should have. These define on which
                properties the Product's Product Variants will differ.
              type: array
              items:
                required:
                  - title
                properties:
                  title:
                    description: The title to identify the Product Option by.
                    type: string
            variants:
              description: A list of Product Variants to create with the Product.
              type: array
              items:
                required:
                  - title
                properties:
                  title:
                    description: The title to identify the Product Variant by.
                    type: string
                  sku:
                    description: The unique SKU for the Product Variant.
                    type: string
                  ean:
                    description: The EAN number of the item.
                    type: string
                  upc:
                    description: The UPC number of the item.
                    type: string
                  barcode:
                    description: A generic GTIN field for the Product Variant.
                    type: string
                  hs_code:
                    description: The Harmonized System code for the Product Variant.
                    type: string
                  inventory_quantity:
                    description: The amount of stock kept for the Product Variant.
                    type: integer
                    default: 0
                  allow_backorder:
                    description: >-
                      Whether the Product Variant can be purchased when out of
                      stock.
                    type: boolean
                  manage_inventory:
                    description: >-
                      Whether Medusa should keep track of the inventory for this
                      Product Variant.
                    type: boolean
                  weight:
                    description: The wieght of the Product Variant.
                    type: number
                  length:
                    description: The length of the Product Variant.
                    type: number
                  height:
                    description: The height of the Product Variant.
                    type: number
                  width:
                    description: The width of the Product Variant.
                    type: number
                  origin_country:
                    description: The country of origin of the Product Variant.
                    type: string
                  mid_code:
                    description: >-
                      The Manufacturer Identification code for the Product
                      Variant.
                    type: string
                  material:
                    description: The material composition of the Product Variant.
                    type: string
                  metadata:
                    description: >-
                      An optional set of key-value pairs with additional
                      information.
                    type: object
                  prices:
                    type: array
                    items:
                      required:
                        - amount
                      properties:
                        region_id:
                          description: >-
                            The ID of the Region for which the price is used.
                            Only required if currency_code is not provided.
                          type: string
                        currency_code:
                          description: >-
                            The 3 character ISO currency code for which the
                            price will be used. Only required if region_id is
                            not provided.
                          type: string
                          externalDocs:
                            url: >-
                              https://en.wikipedia.org/wiki/ISO_4217#Active_codes
                            description: See a list of codes.
                        amount:
                          description: The amount to charge for the Product Variant.
                          type: integer
                        min_quantity:
                          description: >-
                            The minimum quantity for which the price will be
                            used.
                          type: integer
                        max_quantity:
                          description: >-
                            The maximum quantity for which the price will be
                            used.
                          type: integer
                  options:
                    type: array
                    items:
                      required:
                        - value
                      properties:
                        value:
                          description: >-
                            The value to give for the Product Option at the same
                            index in the Product's `options` field.
                          type: string
            weight:
              description: The weight of the Product.
              type: number
            length:
              description: The length of the Product.
              type: number
            height:
              description: The height of the Product.
              type: number
            width:
              description: The width of the Product.
              type: number
            hs_code:
              description: The Harmonized System code for the Product Variant.
              type: string
            origin_country:
              description: The country of origin of the Product.
              type: string
            mid_code:
              description: The Manufacturer Identification code for the Product.
              type: string
            material:
              description: The material composition of the Product.
              type: string
            metadata:
              description: An optional set of key-value pairs with additional information.
              type: object
  x-codeSamples:
    - lang: JavaScript
      label: JS Client
      source:
        $ref: ../code_samples/JavaScript/products/postundefined
    - lang: Shell
      label: cURL
      source:
        $ref: ../code_samples/Shell/products/postundefined
  security:
    - api_token: []
    - cookie_auth: []
  tags:
    - Product
  responses:
    '200':
      description: OK
      content:
        application/json:
          schema:
            properties:
              product:
                $ref: ../components/schemas/product.yaml
    '400':
      $ref: ../components/responses/400_error.yaml
    '401':
      $ref: ../components/responses/unauthorized.yaml
    '404':
      $ref: ../components/responses/not_found_error.yaml
    '409':
      $ref: ../components/responses/invalid_state_error.yaml
    '422':
      $ref: ../components/responses/invalid_request_error.yaml
    '500':
      $ref: ../components/responses/500_error.yaml
get:
  operationId: GetProducts
  summary: List Products
  description: Retrieves a list of Product
  x-authenticated: true
  parameters:
    - in: query
      name: q
      description: >-
        Query used for searching product title and description, variant title
        and sku, and collection title.
      schema:
        type: string
    - in: query
      name: discount_condition_id
      description: The discount condition id on which to filter the product.
      schema:
        type: string
    - in: query
      name: id
      style: form
      explode: false
      description: Filter by product IDs.
      schema:
        oneOf:
          - type: string
            description: ID of the product to search for.
          - type: array
            items:
              type: string
              description: ID of a product.
    - in: query
      name: status
      style: form
      explode: false
      description: Status to search for
      schema:
        type: array
        items:
          type: string
          enum:
            - draft
            - proposed
            - published
            - rejected
    - in: query
      name: collection_id
      style: form
      explode: false
      description: Collection ids to search for.
      schema:
        type: array
        items:
          type: string
    - in: query
      name: tags
      style: form
      explode: false
      description: Tag IDs to search for
      schema:
        type: array
        items:
          type: string
    - in: query
      name: price_list_id
      style: form
      explode: false
      description: Price List IDs to search for
      schema:
        type: array
        items:
          type: string
    - in: query
      name: sales_channel_id
      style: form
      explode: false
      description: Sales Channel IDs to filter products by
      schema:
        type: array
        items:
          type: string
    - in: query
      name: type_id
      style: form
      explode: false
      description: Type IDs to filter products by
      schema:
        type: array
        items:
          type: string
    - in: query
      name: title
      description: title to search for.
      schema:
        type: string
    - in: query
      name: description
      description: description to search for.
      schema:
        type: string
    - in: query
      name: handle
      description: handle to search for.
      schema:
        type: string
    - in: query
      name: is_giftcard
      description: Search for giftcards using is_giftcard=true.
      schema:
        type: boolean
    - in: query
      name: created_at
      description: Date comparison for when resulting products were created.
      schema:
        type: object
        properties:
          lt:
            type: string
            description: filter by dates less than this date
            format: date
          gt:
            type: string
            description: filter by dates greater than this date
            format: date
          lte:
            type: string
            description: filter by dates less than or equal to this date
            format: date
          gte:
            type: string
            description: filter by dates greater than or equal to this date
            format: date
    - in: query
      name: updated_at
      description: Date comparison for when resulting products were updated.
      schema:
        type: object
        properties:
          lt:
            type: string
            description: filter by dates less than this date
            format: date
          gt:
            type: string
            description: filter by dates greater than this date
            format: date
          lte:
            type: string
            description: filter by dates less than or equal to this date
            format: date
          gte:
            type: string
            description: filter by dates greater than or equal to this date
            format: date
    - in: query
      name: deleted_at
      description: Date comparison for when resulting products were deleted.
      schema:
        type: object
        properties:
          lt:
            type: string
            description: filter by dates less than this date
            format: date
          gt:
            type: string
            description: filter by dates greater than this date
            format: date
          lte:
            type: string
            description: filter by dates less than or equal to this date
            format: date
          gte:
            type: string
            description: filter by dates greater than or equal to this date
            format: date
    - in: query
      name: offset
      description: How many products to skip in the result.
      schema:
        type: integer
        default: 0
    - in: query
      name: limit
      description: Limit the number of products returned.
      schema:
        type: integer
        default: 50
    - in: query
      name: expand
      description: >-
        (Comma separated) Which fields should be expanded in each product of the
        result.
      schema:
        type: string
    - in: query
      name: fields
      description: >-
        (Comma separated) Which fields should be included in each product of the
        result.
      schema:
        type: string
  x-codeSamples:
    - lang: JavaScript
      label: JS Client
      source:
        $ref: ../code_samples/JavaScript/products/getundefined
    - lang: Shell
      label: cURL
      source:
        $ref: ../code_samples/Shell/products/getundefined
  security:
    - api_token: []
    - cookie_auth: []
  tags:
    - Product
  responses:
    '200':
      description: OK
      content:
        application/json:
          schema:
            properties:
              products:
                type: array
                items:
                  $ref: ../components/schemas/product.yaml
              count:
                type: integer
                description: The total number of items available
              offset:
                type: integer
                description: The number of items skipped before these items
              limit:
                type: integer
                description: The number of items per page
    '400':
      $ref: ../components/responses/400_error.yaml
    '401':
      $ref: ../components/responses/unauthorized.yaml
    '404':
      $ref: ../components/responses/not_found_error.yaml
    '409':
      $ref: ../components/responses/invalid_state_error.yaml
    '422':
      $ref: ../components/responses/invalid_request_error.yaml
    '500':
      $ref: ../components/responses/500_error.yaml
