delete:
  operationId: DeleteProductsProduct
  summary: Delete a Product
  description: Deletes a Product and it's associated Product Variants.
  x-authenticated: true
  parameters:
    - in: path
      name: id
      required: true
      description: The ID of the Product.
      schema:
        type: string
  x-codeSamples:
    - lang: JavaScript
      label: JS Client
      source:
        $ref: ../code_samples/JavaScript/products_{id}/deleteundefined
    - lang: Shell
      label: cURL
      source:
        $ref: ../code_samples/Shell/products_{id}/deleteundefined
  security:
    - api_token: []
    - cookie_auth: []
  tags:
    - Product
  responses:
    '200':
      description: OK
      content:
        application/json:
          schema:
            $ref: ../components/schemas/AdminProductsDeleteRes.yaml
    '400':
      $ref: ../components/responses/400_error.yaml
    '401':
      $ref: ../components/responses/unauthorized.yaml
    '404':
      $ref: ../components/responses/not_found_error.yaml
    '409':
      $ref: ../components/responses/invalid_state_error.yaml
    '422':
      $ref: ../components/responses/invalid_request_error.yaml
    '500':
      $ref: ../components/responses/500_error.yaml
get:
  operationId: GetProductsProduct
  summary: Get a Product
  description: Retrieves a Product.
  x-authenticated: true
  parameters:
    - in: path
      name: id
      required: true
      description: The ID of the Product.
      schema:
        type: string
  x-codeSamples:
    - lang: JavaScript
      label: JS Client
      source:
        $ref: ../code_samples/JavaScript/products_{id}/getundefined
    - lang: Shell
      label: cURL
      source:
        $ref: ../code_samples/Shell/products_{id}/getundefined
  security:
    - api_token: []
    - cookie_auth: []
  tags:
    - Product
  responses:
    '200':
      description: OK
      content:
        application/json:
          schema:
            $ref: ../components/schemas/AdminProductsRes.yaml
    '400':
      $ref: ../components/responses/400_error.yaml
    '401':
      $ref: ../components/responses/unauthorized.yaml
    '404':
      $ref: ../components/responses/not_found_error.yaml
    '409':
      $ref: ../components/responses/invalid_state_error.yaml
    '422':
      $ref: ../components/responses/invalid_request_error.yaml
    '500':
      $ref: ../components/responses/500_error.yaml
post:
  operationId: PostProductsProduct
  summary: Update a Product
  description: Updates a Product
  x-authenticated: true
  parameters:
    - in: path
      name: id
      required: true
      description: The ID of the Product.
      schema:
        type: string
  requestBody:
    content:
      application/json:
        schema:
          $ref: ../components/schemas/AdminPostProductsProductReq.yaml
  x-codeSamples:
    - lang: JavaScript
      label: JS Client
      source:
        $ref: ../code_samples/JavaScript/products_{id}/postundefined
    - lang: Shell
      label: cURL
      source:
        $ref: ../code_samples/Shell/products_{id}/postundefined
  security:
    - api_token: []
    - cookie_auth: []
  tags:
    - Product
  responses:
    '200':
      description: OK
      content:
        application/json:
          schema:
            $ref: ../components/schemas/AdminProductsRes.yaml
    '400':
      $ref: ../components/responses/400_error.yaml
    '401':
      $ref: ../components/responses/unauthorized.yaml
    '404':
      $ref: ../components/responses/not_found_error.yaml
    '409':
      $ref: ../components/responses/invalid_state_error.yaml
    '422':
      $ref: ../components/responses/invalid_request_error.yaml
    '500':
      $ref: ../components/responses/500_error.yaml
