delete:
  operationId: DeleteProductsProductVariantsVariant
  summary: Delete a Product Variant
  description: Deletes a Product Variant.
  x-authenticated: true
  parameters:
    - in: path
      name: id
      required: true
      description: The ID of the Product.
      schema:
        type: string
    - in: path
      name: variant_id
      required: true
      description: The ID of the Product Variant.
      schema:
        type: string
  x-codeSamples:
    - lang: JavaScript
      label: JS Client
      source:
        $ref: >-
          ../code_samples/JavaScript/products_{id}_variants_{variant_id}/deleteundefined
    - lang: Shell
      label: cURL
      source:
        $ref: >-
          ../code_samples/Shell/products_{id}_variants_{variant_id}/deleteundefined
  security:
    - api_token: []
    - cookie_auth: []
  tags:
    - Product
  responses:
    '200':
      description: OK
      content:
        application/json:
          schema:
            type: object
            properties:
              variant_id:
                type: string
                description: The ID of the deleted Product Variant.
              object:
                type: string
                description: The type of the object that was deleted.
                default: variant
              deleted:
                type: boolean
                description: Whether or not the items were deleted.
                default: true
              product:
                $ref: ../components/schemas/product.yaml
    '400':
      $ref: ../components/responses/400_error.yaml
    '401':
      $ref: ../components/responses/unauthorized.yaml
    '404':
      $ref: ../components/responses/not_found_error.yaml
    '409':
      $ref: ../components/responses/invalid_state_error.yaml
    '422':
      $ref: ../components/responses/invalid_request_error.yaml
    '500':
      $ref: ../components/responses/500_error.yaml
post:
  operationId: PostProductsProductVariantsVariant
  summary: Update a Product Variant
  description: Update a Product Variant.
  x-authenticated: true
  parameters:
    - in: path
      name: id
      required: true
      description: The ID of the Product.
      schema:
        type: string
    - in: path
      name: variant_id
      required: true
      description: The ID of the Product Variant.
      schema:
        type: string
  requestBody:
    content:
      application/json:
        schema:
          type: object
          required:
            - prices
          properties:
            title:
              description: The title to identify the Product Variant by.
              type: string
            sku:
              description: The unique SKU for the Product Variant.
              type: string
            ean:
              description: The EAN number of the item.
              type: string
            upc:
              description: The UPC number of the item.
              type: string
            barcode:
              description: A generic GTIN field for the Product Variant.
              type: string
            hs_code:
              description: The Harmonized System code for the Product Variant.
              type: string
            inventory_quantity:
              description: The amount of stock kept for the Product Variant.
              type: integer
            allow_backorder:
              description: Whether the Product Variant can be purchased when out of stock.
              type: boolean
            manage_inventory:
              description: >-
                Whether Medusa should keep track of the inventory for this
                Product Variant.
              type: boolean
            weight:
              description: The weight of the Product Variant.
              type: number
            length:
              description: The length of the Product Variant.
              type: number
            height:
              description: The height of the Product Variant.
              type: number
            width:
              description: The width of the Product Variant.
              type: number
            origin_country:
              description: The country of origin of the Product Variant.
              type: string
            mid_code:
              description: The Manufacturer Identification code for the Product Variant.
              type: string
            material:
              description: The material composition of the Product Variant.
              type: string
            metadata:
              description: An optional set of key-value pairs with additional information.
              type: object
            prices:
              type: array
              items:
                required:
                  - amount
                properties:
                  id:
                    description: The ID of the price.
                    type: string
                  region_id:
                    description: >-
                      The ID of the Region for which the price is used. Only
                      required if currency_code is not provided.
                    type: string
                  currency_code:
                    description: >-
                      The 3 character ISO currency code for which the price will
                      be used. Only required if region_id is not provided.
                    type: string
                    externalDocs:
                      url: https://en.wikipedia.org/wiki/ISO_4217#Active_codes
                      description: See a list of codes.
                  amount:
                    description: The amount to charge for the Product Variant.
                    type: integer
                  min_quantity:
                    description: The minimum quantity for which the price will be used.
                    type: integer
                  max_quantity:
                    description: The maximum quantity for which the price will be used.
                    type: integer
            options:
              type: array
              items:
                required:
                  - option_id
                  - value
                properties:
                  option_id:
                    description: The ID of the Product Option to set the value for.
                    type: string
                  value:
                    description: The value to give for the Product Option.
                    type: string
  x-codeSamples:
    - lang: JavaScript
      label: JS Client
      source:
        $ref: >-
          ../code_samples/JavaScript/products_{id}_variants_{variant_id}/postundefined
    - lang: Shell
      label: cURL
      source:
        $ref: >-
          ../code_samples/Shell/products_{id}_variants_{variant_id}/postundefined
  security:
    - api_token: []
    - cookie_auth: []
  tags:
    - Product
  responses:
    '200':
      description: OK
      content:
        application/json:
          schema:
            type: object
            properties:
              product:
                $ref: ../components/schemas/product.yaml
    '400':
      $ref: ../components/responses/400_error.yaml
    '401':
      $ref: ../components/responses/unauthorized.yaml
    '404':
      $ref: ../components/responses/not_found_error.yaml
    '409':
      $ref: ../components/responses/invalid_state_error.yaml
    '422':
      $ref: ../components/responses/invalid_request_error.yaml
    '500':
      $ref: ../components/responses/500_error.yaml
