[[redirects]]
  from = "/api"
  to = "/api/store"

[[redirects]]
  from = "/api/store/*"
  to = "/api/store"

[[redirects]]
  from = "/api/admin/*"
  to = "/api/admin"

[[redirects]]
  from = "/how-to/headless-ecommerce-store-with-gatsby-contentful-medusa"
  to = "/add-plugins/contentful"

[[redirects]]
  from = "/how-to/deploying-on-heroku"
  to = "/deployments/server/deploying-on-heroku"

[[redirects]]
  from = "/admin/introduction"
  to = "/admin/quickstart"

[[redirects]]
  from = "/admin/quickstart/quick-start"
  to = "/admin/quickstart"

[[redirects]]
  from = "/admin/quickstart"
  to = "/admin/quickstart"

[[redirects]]
  from = "/quickstart/starters/nextjs-medusa-starter"
  to = "/starters/nextjs-medusa-starter"

[[redirects]]
  from = "/quickstart/starters/gatsby-medusa-starter"
  to = "/starters/gatsby-medusa-starter"

[[redirects]]
  from = "/how-to/create-medusa-app"
  to = "/usage/create-medusa-app"

[[redirects]]
  from = "/guides/plugins"
  to = "/advanced/backend/plugins/overview"

[[redirects]]
  from = "/how-to/deploying-admin-on-netlify"
  to = "/deployments/admin/deploying-on-netlify"

[[redirects]]
  from = "/how-to/deploying-on-digital-ocean/"
  to = "/deployments/server/deploying-on-digital-ocean"

[[redirects]]
  from = "/how-to/deploying-on-qovery/"
  to = "/deployments/server/deploying-on-qovery"

[[redirects]]
  from = "/guides/fulfillment-api"
  to = "/advanced/backend/shipping/add-fulfillment-provider"

[[redirects]]
  from = "/guides/checkouts"
  to = "/advanced/storefront/how-to-implement-checkout-flow"

[[redirects]]
  from = "/guides/checkouts"
  to = "/advanced/storefront/how-to-implement-checkout-flow"